// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuizSystem_backend.Models;

#nullable disable

namespace QuizSystem_backend.Migrations
{
    [DbContext(typeof(QuizSystemDbContext))]
    [Migration("20250621135725_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuizSystem_backend.Models.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("AnswerOrder")
                        .HasColumnType("int")
                        .HasColumnName("thu_tu");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("noi_dung");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit")
                        .HasColumnName("dung");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ma_cau_hoi");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("CauTraLoi", (string)null);
                });

            modelBuilder.Entity("QuizSystem_backend.Models.Chapter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("CourseClassId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ma_mon_hoc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("mo_ta");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_chuong");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id");

                    b.HasIndex("CourseClassId");

                    b.ToTable("Chuong", (string)null);
                });

            modelBuilder.Entity("QuizSystem_backend.Models.CourseClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ClassCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ma_lop");

                    b.Property<int>("Credit")
                        .HasColumnType("int")
                        .HasColumnName("so_tin_chi");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_lop");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("trang_thai");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mon_hoc");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ma_giao_vien");

                    b.HasKey("Id");

                    b.HasIndex("ClassCode")
                        .IsUnique();

                    b.HasIndex("TeacherId");

                    b.ToTable("LopHocPhan", (string)null);
                });

            modelBuilder.Entity("QuizSystem_backend.Models.Exam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int")
                        .HasColumnName("thoi_gian_lam_bai");

                    b.Property<string>("ExamCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ma_de");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_bai_thi");

                    b.Property<int>("NumberOfQuestions")
                        .HasColumnType("int")
                        .HasColumnName("so_cau_hoi");

                    b.Property<Guid>("RoomExamId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ma_phong_thi");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_bat_dau");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id");

                    b.HasIndex("ExamCode")
                        .IsUnique();

                    b.HasIndex("RoomExamId");

                    b.ToTable("DeThi", (string)null);
                });

            modelBuilder.Entity("QuizSystem_backend.Models.ExamQuestion", b =>
                {
                    b.Property<Guid>("ExamId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ma_bai_thi");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ma_cau_hoi");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("thu_tu");

                    b.Property<float>("Score")
                        .HasColumnType("real")
                        .HasColumnName("diem_so");

                    b.HasKey("ExamId", "QuestionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("ChiTietDeThi", (string)null);
                });

            modelBuilder.Entity("QuizSystem_backend.Models.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("ChapterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ma_chuong");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("noi_dung");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ma_nguoi_tao");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("do_kho");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("hinh_anh");

                    b.Property<Guid?>("QuestionBankId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ma_ngan_hang_cau_hoi");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("trang_thai");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("chu_de");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("loai_cau_hoi");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("QuestionBankId");

                    b.ToTable("CauHoi", (string)null);
                });

            modelBuilder.Entity("QuizSystem_backend.Models.QuestionBank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("CourseClassId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("mon_hoc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("mo_ta");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_ngan_hang");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id");

                    b.HasIndex("CourseClassId");

                    b.ToTable("NganHangCauHoi", (string)null);
                });

            modelBuilder.Entity("QuizSystem_backend.Models.RoomExam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("CourseClassId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ma_lop_hoc_phan");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_ket_thuc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_phong");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_bat_dau");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id");

                    b.HasIndex("CourseClassId");

                    b.ToTable("PhongThi", (string)null);
                });

            modelBuilder.Entity("QuizSystem_backend.Models.StudentCourseClass", b =>
                {
                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ma_sinh_vien");

                    b.Property<Guid>("CourseClassId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ma_lop_hoc_phan");

                    b.Property<float?>("Grade")
                        .HasColumnType("real")
                        .HasColumnName("diem_so");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ghi_chu");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("trang_thai");

                    b.HasKey("StudentId", "CourseClassId");

                    b.HasIndex("CourseClassId");

                    b.ToTable("SinhVienLopHocPhan", (string)null);
                });

            modelBuilder.Entity("QuizSystem_backend.Models.StudentExam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ma_ket_qua_bai_thi");

                    b.Property<Guid>("CourseClassId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ma_lop_hoc_phan");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int")
                        .HasColumnName("thoi_luong_phut");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ma_bai_thi");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("trang_thai");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ma_sinh_vien");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.HasIndex("StudentId", "CourseClassId");

                    b.ToTable("KetQuaBaiThi", (string)null);
                });

            modelBuilder.Entity("QuizSystem_backend.Models.StudentExamDetail", b =>
                {
                    b.Property<Guid>("AnswerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ma_cau_tra_loi");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ma_cau_hoi");

                    b.Property<Guid>("StudentExamId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ma_ket_qua_bai_thi");

                    b.HasKey("AnswerId", "QuestionId", "StudentExamId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("StudentExamId");

                    b.ToTable("ChiTietKetQuaBaiThi", (string)null);
                });

            modelBuilder.Entity("QuizSystem_backend.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("url_anh");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_sinh");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ho_ten");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit")
                        .HasColumnName("gioi_tinh");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mat_khau");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("so_dien_thoai");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("vai_tro");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("trang_thai");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ten_dang_nhap");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("TaiKhoan", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("QuizSystem_backend.Models.Student", b =>
                {
                    b.HasBaseType("QuizSystem_backend.Models.User");

                    b.Property<string>("Facutly")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("khoa");

                    b.Property<bool>("IsFirstTimeLogin")
                        .HasColumnType("bit")
                        .HasColumnName("dang_nhap_lan_dau");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma_sinh_vien");

                    b.ToTable("SinhVien", (string)null);
                });

            modelBuilder.Entity("QuizSystem_backend.Models.Teacher", b =>
                {
                    b.HasBaseType("QuizSystem_backend.Models.User");

                    b.Property<string>("Facutly")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("khoa");

                    b.Property<bool>("IsFirstTimeLogin")
                        .HasColumnType("bit")
                        .HasColumnName("dang_nhap_lan_dau");

                    b.Property<string>("TeacherCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma_giao_vien");

                    b.ToTable("GiangVien", (string)null);
                });

            modelBuilder.Entity("QuizSystem_backend.Models.Answer", b =>
                {
                    b.HasOne("QuizSystem_backend.Models.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("QuizSystem_backend.Models.Chapter", b =>
                {
                    b.HasOne("QuizSystem_backend.Models.CourseClass", "Course")
                        .WithMany("Chapters")
                        .HasForeignKey("CourseClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("QuizSystem_backend.Models.CourseClass", b =>
                {
                    b.HasOne("QuizSystem_backend.Models.Teacher", "Teacher")
                        .WithMany("CourseClasses")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("QuizSystem_backend.Models.Exam", b =>
                {
                    b.HasOne("QuizSystem_backend.Models.RoomExam", "RoomExam")
                        .WithMany("Exams")
                        .HasForeignKey("RoomExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomExam");
                });

            modelBuilder.Entity("QuizSystem_backend.Models.ExamQuestion", b =>
                {
                    b.HasOne("QuizSystem_backend.Models.Exam", "Exam")
                        .WithMany("ExamQuestions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizSystem_backend.Models.Question", "Question")
                        .WithMany("ExamQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("QuizSystem_backend.Models.Question", b =>
                {
                    b.HasOne("QuizSystem_backend.Models.Chapter", "Chapter")
                        .WithMany("Question")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuizSystem_backend.Models.Teacher", "Teacher")
                        .WithMany("Questions")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuizSystem_backend.Models.QuestionBank", "QuestionBank")
                        .WithMany("questions")
                        .HasForeignKey("QuestionBankId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Chapter");

                    b.Navigation("QuestionBank");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("QuizSystem_backend.Models.QuestionBank", b =>
                {
                    b.HasOne("QuizSystem_backend.Models.CourseClass", "Course")
                        .WithMany("QuestionBanks")
                        .HasForeignKey("CourseClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("QuizSystem_backend.Models.RoomExam", b =>
                {
                    b.HasOne("QuizSystem_backend.Models.CourseClass", "Course")
                        .WithMany("RoomExams")
                        .HasForeignKey("CourseClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("QuizSystem_backend.Models.StudentCourseClass", b =>
                {
                    b.HasOne("QuizSystem_backend.Models.CourseClass", "Course")
                        .WithMany()
                        .HasForeignKey("CourseClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuizSystem_backend.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("QuizSystem_backend.Models.StudentExam", b =>
                {
                    b.HasOne("QuizSystem_backend.Models.Exam", "Exam")
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuizSystem_backend.Models.StudentCourseClass", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId", "CourseClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("QuizSystem_backend.Models.StudentExamDetail", b =>
                {
                    b.HasOne("QuizSystem_backend.Models.Answer", "Answer")
                        .WithMany()
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuizSystem_backend.Models.Question", "Question")
                        .WithMany("StudentExamDetails")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuizSystem_backend.Models.StudentExam", "StudentExam")
                        .WithMany("StudentExamDetails")
                        .HasForeignKey("StudentExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("Question");

                    b.Navigation("StudentExam");
                });

            modelBuilder.Entity("QuizSystem_backend.Models.Student", b =>
                {
                    b.HasOne("QuizSystem_backend.Models.User", null)
                        .WithOne()
                        .HasForeignKey("QuizSystem_backend.Models.Student", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuizSystem_backend.Models.Teacher", b =>
                {
                    b.HasOne("QuizSystem_backend.Models.User", null)
                        .WithOne()
                        .HasForeignKey("QuizSystem_backend.Models.Teacher", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuizSystem_backend.Models.Chapter", b =>
                {
                    b.Navigation("Question");
                });

            modelBuilder.Entity("QuizSystem_backend.Models.CourseClass", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("QuestionBanks");

                    b.Navigation("RoomExams");
                });

            modelBuilder.Entity("QuizSystem_backend.Models.Exam", b =>
                {
                    b.Navigation("ExamQuestions");
                });

            modelBuilder.Entity("QuizSystem_backend.Models.Question", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("ExamQuestions");

                    b.Navigation("StudentExamDetails");
                });

            modelBuilder.Entity("QuizSystem_backend.Models.QuestionBank", b =>
                {
                    b.Navigation("questions");
                });

            modelBuilder.Entity("QuizSystem_backend.Models.RoomExam", b =>
                {
                    b.Navigation("Exams");
                });

            modelBuilder.Entity("QuizSystem_backend.Models.StudentExam", b =>
                {
                    b.Navigation("StudentExamDetails");
                });

            modelBuilder.Entity("QuizSystem_backend.Models.Teacher", b =>
                {
                    b.Navigation("CourseClasses");

                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
